# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c323c57a18393375748193ebd4e96bac72931ed8e8472edf8bf8493bcb00fb08219c610b20b763d2228dd6db11b2c0867a5e81483176209a0fe258ca3e78d60

test:
  secret_key_base: 36ac7cd1fe5257003ca6c7b96b3e2449e07faff3c379a641a6f5bc6010486eba1cfcb499c084791a2280c01fda1543e270e650965a0822b849fd8c78e61bafbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
